import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Analytics } from '@vercel/analytics/react';
import Providers from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guilherme M. Toso",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {

    return (
      <html lang="en">
      <body className={`${inter.className} overflow-y-scroll`}>
      <Providers>
          {children}
      </Providers>
      <Analytics></Analytics>
      </body>
      </html>
  );
}